%% Example solve muscle redundancy with an MRI model

clear all;

%% Input information
% Install instructions:
%   Add the main path ...\solvemuscleredundancy_dev to your matlab folder,
%   using the following command (in my case)
ExamplePath = pwd;
DataPath = [pwd '\Data'];
% Path up 2 folders is main path
idcs   = strfind(ExamplePath,'\');
newdir = ExamplePath(1:idcs(end)-1);
idcs   = strfind(newdir,'\');
MainPath = newdir(1:idcs(end)-1);
% Add all folders under main path
addpath(genpath(MainPath));

% Add here the paths of IK, ID , US and EMG data trials you want to work with
% As example we use trial 1 2 & 4 
Misc.IKfile = {fullfile(DataPath,'trial_1_IK.mot')};
Misc.IDfile = {fullfile(DataPath,'trial_1_ID.mot')};
model_path  = fullfile(DataPath,'model.osim');
Out_path    = fullfile(ExamplePath,'Results');                    % folder to store results

% Get start and end time of the different files (you can also specify this
% manually)
time = [0 9999];  % (selects the full file) 

%% Settings
Misc.DofNames_Input={'ankle_angle_l'};    % select the DOFs you want to include in the optimization
Misc.MuscleNames_Input = {'med_gas_l','lat_gas_l','soleus_l','tib_ant_l'}; % select muscles
% MRS Bool: Select if you want to run the generic muscle redundancy solver
Misc.MRSBool = 1;
% output name
Misc.OutName = 'Minimal_';
%% Run muscle tendon estimator:
[Results,DatStore,Misc] = MuscleTendonEstimator(model_path,time,Out_path,Misc);

% Save the results structure where you want
save('Results.mat','Results');

%% Example: evaluate results
F = Results.TForce.genericMRS';
dM = DatStore.MAinterp;

Tm = F.*dM;
figure(); plot(Tm); legend(DatStore.MuscleNames);
ylabel('moment generated by muscles [Nm]');
xlabel('frames');

figure(); plot(Results.Fpe.genericMRS); legend(DatStore.MuscleNames);
